# Generated by Django 5.1.7 on 2025-06-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_signin", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
