# Generated by Django 5.1.7 on 2025-06-17 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adresse', models.CharField(max_length=255)),
                ('imagePrincipale', models.ImageField(blank=True, null=True, upload_to='annonces/')),
                ('date_postee', models.DateTimeField(auto_now_add=True)),
                ('lien', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.annonce')),
            ],
        ),
    ]
