# Generated by Django 5.1.7 on 2025-06-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageannonce',
            old_name='image',
            new_name='imageSupplementaireFichier',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='imagePrincipale',
        ),
        migrations.AddField(
            model_name='imageannonce',
            name='estImagePrincipale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imageannonce',
            name='imageSupplementaireUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
