# Generated by Django 5.1.7 on 2025-06-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_rename_image_imageannonce_imagesupplementairefichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
