# Generated by Django 5.1.7 on 2025-06-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_annonce_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='a_discuter',
            field=models.CharField(default='', max_length=255),
        ),
    ]
