# Generated by Django 5.1.7 on 2025-06-18 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_remove_annonce_a_discuter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='image_url',
            new_name='image_Principale',
        ),
        migrations.RemoveField(
            model_name='imageannonce',
            name='estImagePrincipale',
        ),
        migrations.AddField(
            model_name='imageannonce',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='imageannonce',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annonces.annonce'),
        ),
    ]
